package webFrontCommonUtils;

import java.util.List;
import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

/* Generated by http://www.jsonschema2pojo.org/ */

public class CTL {

	@SerializedName("lines")
	@Expose
	private List<CTLLine> lines = null;

	public List<CTLLine> getLines() {
		return lines;
	}

	public void setLines(List<CTLLine> lines) {
		this.lines = lines;
	}

}