package webFrontCommonUtils;

import java.util.List;
import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

/* Generated by http://www.jsonschema2pojo.org/ */

public class DPT {

	@SerializedName("lines")
	@Expose
	private List<DPTLine> lines = null;

	public List<DPTLine> getLines() {
		return lines;
	}

	public void setLines(List<DPTLine> lines) {
		this.lines = lines;
	}

}
